spring.application.name=studentsmarks
spring.datasource.url=jdbc:postgresql://localhost:5432/students_marks_db
spring.datasource.username=postgres
spring.datasource.password=nithya@12

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true